# Generated by Django 5.2.13 on 2026-04-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventionDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_name', models.CharField(max_length=255)),
                ('inventor_email', models.EmailField(max_length=254)),
                ('invention_title', models.CharField(max_length=255)),
                ('invention_description', models.TextField()),
                ('technology_field', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_invention', models.DateField()),
                ('inventors', models.TextField(blank=True, default='')),
                ('patent_status', models.CharField(blank=True, choices=[('none', 'No patent filed'), ('pending', 'Patent pending'), ('granted', 'Patent granted')], default='none', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
