# Generated by Django 5.2.12 on 2026-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE accounts_user
                ADD COLUMN IF NOT EXISTS is_email_verified boolean NOT NULL DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE accounts_user
                DROP COLUMN IF EXISTS is_email_verified;
            """,
        ),
    ]
