# Generated by Django 5.2.12 on 2026-03-18 16:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('office_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('therapeutic_focus_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Comma-separated list of therapeutic focus areas (e.g., 'Oncology', 'Cardiology')", size=None)),
                ('trl_range_interest_min', models.IntegerField(blank=True, help_text='Minimum Technology Readiness Level (TRL) of interest (1-9)', null=True)),
                ('trl_range_interest_max', models.IntegerField(blank=True, help_text='Maximum Technology Readiness Level (TRL) of interest (1-9)', null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'university'}, on_delete=django.db.models.deletion.CASCADE, related_name='ttoprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
