# Generated by Django 5.2.8 on 2026-03-30 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_user_options_user_created_at_user_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, default="", max_length=255)),
                ("patent_count", models.IntegerField(default=0)),
                (
                    "stage",
                    models.CharField(
                        choices=[("new", "New"), ("experienced", "Experienced")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("seeking_funding", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("funding_details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_profiles",
            },
        ),
    ]
